### ISSUE TITLE
[bug/signinApi] 가입된 아이디가 없을 때 에러 메시지 이상

### ISSUE THREAD

**Issue by manOfBackend** [Everyone-s-delivery/Web#36]
비밀번호가 틀렸을 때는 잘 나오지만
가입된 아이디가 없을 때는 

![image](https://user-images.githubusercontent.com/74768098/153891243-32cca78d-60ce-4550-86a6-8d5b5e9939af.png)

애매한 응답이 나옵니다.

**Comment by manOfBackend** [comment]
그리고 유즈케이스에 따른 errorCode 유형 정보가 필요합니다.

**Comment by manOfBackend** [comment]
로그인 성공시에도
![image](https://user-images.githubusercontent.com/74768098/153897318-603f0cc8-0e45-4873-ae58-f5d66a1beda4.png)
swagger의 response 200과는 타입이 다르네요.

**Comment by rnjstjdgh** [comment]
# 정리

### 1.  유즈케이스에 따른 errorCode 유형 정보 세분화
* 처음부터 유즈케이스를 엄밀하게 정하고 개발하는 관점이라기 보단 구현하면서 요구사항을 구체화 하는 관점이기 때문에 처음부터   errorCode 유형 정보 세분화는 어려울 것임
* 처음 개발 시에는 errorCode 를 러프하게 잡고 요구사항이 구체화 될 수록 세분화 하는 방식을 선택
    * 지금처럼 필요하다고 생각되는 errorCode 유형이 생기면 협의 하에 그때그때 추가하는 것으로

### 2.  Swagger 이외의 별도 문서 작성
* Swagger의 한계
    1.  정상 응답 말고 예외에 대한 모든 case의 응답을 자동으로 문서화 하기 어렵다.
    2.  응답 방법을 공통화 한 경우 추상화 된 타입을 응답 타입으로 지정하게 되면, Swagger는 실제 구현체의 응답 형태를 노출하지 못한다.
    3. 등등...
* 대안
    * swagger는 문서에 대한 요약본 + api test 기능
    * 디테일 문서는 별도 notion을 통해 작성하고 swagger에 링크를 달아 연결

**Comment by manOfBackend** [comment]
위 내용으로 합의하였습니다.

**Comment by rnjstjdgh** [comment]
문서화를 위한 도구는 어떤것을 쓰면 좋을지와 REST API 문서 템플릿을 정해두는 것이 앞으로 작업에 도움이 될 것 같습니다.
